# 此开源项目地址 https://github.com/lowlighter/metrics
# 生成的数据卡通过 jsDelivr 嵌入 README：
# https://cdn.jsdelivr.net/gh/NotSleeply/NotSleeply/github-metrics/*.svg

name: GitHub Metrics

on:
  schedule:
    - cron: "0 0 * * *"
    # https://docs.github.com/zh/actions/using-workflows/events-that-trigger-workflows#schedule
  workflow_dispatch:

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      # 基础信息（顺带几个小插件）
      - name: base
        uses: lowlighter/metrics@latest
        with:
          filename: github-metrics/base.svg
          # Your GitHub token
          token: ${{ secrets.METRICS_TOKEN }}
          # Options
          user: NotSleeply
          template: classic
          config_timezone: Asia/Shanghai
          base: "header, activity, community, repositories"
          # 此插件为文档中的 👨‍💻 Lines of code changed
          plugin_lines: yes
          # 此插件为文档中的 🙋 Introduction
          plugin_introduction: yes
          # 此插件为文档中的 🎫 Gists
          plugin_gists: yes

      # 📅 Isometric commit calendar（全年等距提交日历）
      - name: Full-year calendar
        uses: lowlighter/metrics@latest
        with:
          filename: github-metrics/isocalendar.fullyear.svg
          token: ${{ secrets.METRICS_TOKEN }}
          # 不添加基础信息
          base: ""
          # 使用此插件
          plugin_isocalendar: yes
          # 设置成显示整年
          plugin_isocalendar_duration: full-year

      # 🈷️ 语言深度分析
      - name: Indepth languages
        uses: lowlighter/metrics@latest
        with:
          filename: github-metrics/languages.indepth.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          plugin_languages: yes
          plugin_languages_ignored: >-
            html, css, tex, less, dockerfile, makefile, qmake, lex, cmake, shell,
            gnuplot
          plugin_languages_indepth: yes
          plugin_languages_details: lines, bytes-size
          plugin_languages_limit: 4
          plugin_languages_analysis_timeout: 15

      # ✨ 星标趋势图
      - name: Stargazers chart
        uses: lowlighter/metrics@latest
        with:
          filename: github-metrics/stargazers.chartist.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          plugin_stargazers: yes
          plugin_stargazers_charts_type: chartist
